name: Build Releases
on:
  workflow_dispatch:
    inputs:
      steamworks_sdk_tag:
        description: 'Steamworks SDK Tag:'
        required: true
        type: string
        default: 'sdk-1.58'
      godotsteam_version:
        description: 'GodotSteam GDExtension Tag:'
        required: true
        type: string
        default: 'v4.4.3-gde'

jobs:
  build-gdextension-release:
    uses: ./.github/workflows/build-gdextension.yml
